name: fullstack-challenge

services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        # image: mysql:8
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        # image: redis:7
        image: redis:alpine3.16
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
